# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check_python_script:
    runs-on: ubuntu-latest # Use the appropriate operating system here

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run Python script
        run: python3 tests/run_tests.py
        # If your Python script fails, it will return a non-zero exit code by default

  notify_on_failure:
    needs: check_python_script
    runs-on: ubuntu-latest
    if: ${{ needs.check_python_script.result == 'failure' }}
    steps:
      - name: Send notification
        run: echo "The Python script failed. Check the logs for details."
