# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check_python_script:
    runs-on: windows-latest # Use the appropriate operating system here

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run Python script
        run: python tests/run_tests.py
        # If your Python script fails, it will return a non-zero exit code by default

      - name: Check whether logs folder exists
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "${{runner.workspace}}/test/logs/*.txt"

      - if: ${{always() && steps.check_files.outputs.files_exists == 'true' }}
        name: Download Artifacts if logs exists
        uses: actions/upload-artifact@v3
        with:
          name: Download New_ATS Test Results %TIME:~0,2%-%TIME:~3,2%-%TIME:~6,2%
          path: ${{runner.workspace}}/test/logs
      - name: Show artifacts
        run: |
          $directory = "logs"

          Get-ChildItem -Path $directory | ForEach-Object {
              if ($_.PSIsContainer -eq $false) {
                  Write-Host "Contents of $($_.Name):"
                  Get-Content $_.FullName
                  Write-Host ""
              }
          }
