# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check_python_script:
    runs-on: ubuntu-latest # Use the appropriate operating system here

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run Python script
        run: python3 tests/run_tests.py
        # If your Python script fails, it will return a non-zero exit code by default

      - name: Check whether logs folder exists
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "${{runner.workspace}}/test/logs/*.txt"

      - if: ${{always() && steps.check_files.outputs.files_exists == 'true' }}
        name: Download Artifacts if logs exists
        uses: actions/upload-artifact@v3
        with:
          name: Download New_ATS Test Results
          path: ${{runner.workspace}}/test/logs
      - name: Show artifacts
        run: |
          @echo off
          set "directory=${{runner.workspace}}/test/logs"

          for %%F in ("%directory%\*") do (
              if exist "%%F" (
                  echo Contents of %%~nxF:
                  type "%%F"
                  echo -------------------------------------
              )
          )
