# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check_python_script:
    runs-on: windows-latest # Use the appropriate operating system here

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run Python script
        run: python tests/run_tests.py
        # If your Python script fails, it will return a non-zero exit code by default

      - name: Check whether logs folder exists
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "${{runner.workspace}}/test/logs/*.txt"

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD_HH-MM-SS
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

      - if: ${{always() && steps.check_files.outputs.files_exists == 'true' }}
        name: Download Artifacts if logs exists
        uses: actions/upload-artifact@v3
        with:
          name: Download New_ATS Test Results
          path: ${{runner.workspace}}/test/logs
      - name: Show artifacts
        run: |
          $directory = "logs"

          Get-ChildItem -Path $directory | ForEach-Object {
              if ($_.PSIsContainer -eq $false) {
                  Write-Host "Contents of $($_.Name):"
                  Get-Content $_.FullName
                  Write-Host "${{steps.current_time.outputs.time}}"
              }
          }
